// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_lang_index from "./routes/[lang]/index.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $AnchorLang from "./islands/AnchorLang.tsx";
import * as $ButtonPrint from "./islands/ButtonPrint.tsx";
import * as $DarkMode from "./islands/DarkMode.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[lang]/index.tsx": $_lang_index,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AnchorLang.tsx": $AnchorLang,
    "./islands/ButtonPrint.tsx": $ButtonPrint,
    "./islands/DarkMode.tsx": $DarkMode,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
